server:
#  配置端口号
  port: 8090
#  配置mybatis
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/information_student?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: true #缓存
  devtools:
    restart:
      enabled: true #开启热配置
      additional-paths: src/main/java #热配置监听目录
mybatis:
  mapper-locations: classpath:com.westos.Information.dao/*.xml #对应mapper映射xml文件的所在路径
  type-aliases-package: com.westos.Information.bean  # 对应实体类的路径
